### ISSUE TITLE
How to populate <tfoot> or <caption>

### ISSUE THREAD

**Issue by dnagirl** [fsi-open/datagrid#56]
So far as I can see, there is no way to populate `<tfoot>` or `<caption>` elements either by configuration or php. If I want datagrid output with a `<tfoot>` that looks like this:

	<tfoot>
		<tr><td colspan="3">
			<a href="http://example.com" role="button"><i class='fa fa-plus></i>New</a>
		</td></tr>
	</tfoot>

how would I do it?

**Comment by chives** [comment]
@dnagirl  Bare datagrid component does not render any templates so you probably want to use https://github.com/fsi-open/datagrid-bundle and its theming capabilities - https://github.com/fsi-open/datagrid-bundle/blob/master/Resources/docs/templating.md

**Comment by dnagirl** [comment]
@chives Sorry about posting this in the wrong spot. I actually am using datagrid-bundle and I've successfully used theming.  I take it that if I want the some part of my `<tfoot>` to be dynamic, I'd have to pass that info in when I declare the theme?  Something like:

    {% datagrid_theme datagrid _self with {'addURL': 'http://example.com'} %}

And then the template would be:

    {% block datagrid %}
    {% spaceless %}
        <table>
            <thead>
                {{ datagrid_header_widget(datagrid) }}
            </thead>
            <tbody>
                {{ datagrid_rowset_widget(datagrid) }}
            </tbody>
            <tfoot>
                <tr><td colspan="3">
                    <a href="{{ addURL }}" role="button"><i class='fa fa-plus></i>New</a>
                </td></tr>
            </tfoot>
       </table>
    {% endspaceless %}
    {% endblock %}
